COMMENT =	library for accessing mail storages in MBox format
DISTNAME =	kmbox-${VERSION}
CATEGORIES =	devel mail

SHARED_LIBS +=	KPim6Mbox                 1.0 # 0.0

WANTLIB += ${COMPILER_LIBCXX} Qt6Core m

LIB_DEPENDS =

.include <bsd.port.mk>
